#!/usr/bin/env bash
# sync-disclosure-config.sh — emit disclosure-config.json from the hand-synced disclosure allow-list.
#
# v1 = HAND-SYNCED (Founder-signed 2026-07-01). The SSOT is the private planning repo
#   neckarshore-planning/docs/reference/repo-attribution-matrix.yaml → key `disclosure`
#   (`named_private` + `product_name_overrides`). Planning is PRIVATE, so it is NOT read at CI
#   time; this script embeds a review-gated, derived copy (R3: matrix is the single source of
#   truth, this is a downstream copy that must be re-synced when the matrix `disclosure` block
#   changes). A later nicety may auto-sync it; v1 is a manual `npm run sync:disclosure-config`.
#
# Output shape (exactly two fields, per work-order §3a):
#   - named_private:     [ "<owner/name>", … ]        the private slugs ALLOWED into the named set.
#   - display_overrides: { "<owner/name>": "<name>" } slug → product display-name map.
#
# HARD RULE (asserted below AND by the unit test): every `named_private` slug MUST also have a
# `display_overrides` entry — a private repo is rendered ONLY as its product name, never its raw
# slug. A `named_private` without an override is a defect (it would leak the private slug), so this
# generator FAILS rather than emit it.
#
# Determinism: `jq -S` sorts object keys and `sort` sorts the array A→Z, so the committed file is
# byte-identical to a re-run (matches the aggregator's `jq -s -S` convention). Re-running must
# produce a no-op diff.
#
# Usage:
#   bash scripts/sync-disclosure-config.sh            # writes ./disclosure-config.json (log → stderr)
#   bash scripts/sync-disclosure-config.sh --stdout   # prints the JSON to stdout, writes nothing
#                                                     # (used by the unit test for a non-destructive
#                                                     #  committed-vs-regenerated byte-identical check)
set -euo pipefail

cd "$(dirname "$0")/.."

OUT="disclosure-config.json"
MODE="${1:-file}"

# --- Hand-synced from repo-attribution-matrix.yaml `disclosure` (Founder-signed 2026-07-01) ---
# named_private: the 5 approved private products (Omnopsis ×3 + Phonesis + Snakeoil-Check). Nothing
# else private is ever named. Adding here without a matching display_overrides entry is a FAILURE
# (HARD RULE).
NAMED_PRIVATE='[
  "neckarshore-mmps/phonesis-voicebank",
  "neckarshore-mmps/snakeoil-check",
  "omnopsis-ai/omnopsis-backend",
  "omnopsis-ai/omnopsis-contracts",
  "omnopsis-ai/omnopsis-frontend"
]'

# display_overrides: slug → product display-name. Public products (board consistency) + the
# approved-private products (disclose the announced fact, withhold the private slug).
DISPLAY_OVERRIDES='{
  "neckarshore-mmps/clearpath": "ClearPath",
  "neckarshore-mmps/mmp-local-seo-performance-hub": "Local SEO Hub",
  "neckarshore-mmps/mmp-prod-or-pretend": "Prod or Pretend",
  "neckarshore-mmps/phonesis-voicebank": "Phonesis",
  "neckarshore-mmps/snakeoil-check": "Snakeoil-Check",
  "neckarshore-mmps/trustscope": "TrustScope",
  "neckarshore-skills/ai-phrase-check": "AI Phrase Check",
  "neckarshore-skills/imap-mailbox-cleanup": "IMAP Mailbox Cleanup",
  "neckarshore-skills/obsidian-vault-autopilot": "Obsidian Vault Autopilot",
  "omnopsis-ai/omnopsis-backend": "Omnopsis",
  "omnopsis-ai/omnopsis-contracts": "Omnopsis",
  "omnopsis-ai/omnopsis-frontend": "Omnopsis"
}'

# HARD-RULE fail-fast: every named_private slug must have a display_overrides entry.
MISSING=$(jq -n --argjson np "$NAMED_PRIVATE" --argjson ov "$DISPLAY_OVERRIDES" \
  '[$np[] | select((. as $s | $ov | has($s)) | not)]')
if [ "$(printf '%s' "$MISSING" | jq 'length')" -ne 0 ]; then
  echo "FATAL: named_private slug(s) without a display_overrides entry (would leak the raw private slug):" >&2
  printf '%s\n' "$MISSING" | jq -r '.[]' >&2
  exit 1
fi

# Build canonical, -S-sorted JSON (array A→Z, object keys sorted).
JSON=$(jq -S -n --argjson np "$NAMED_PRIVATE" --argjson ov "$DISPLAY_OVERRIDES" \
  '{named_private: ($np | sort), display_overrides: $ov}')

NP_COUNT=$(printf '%s' "$NAMED_PRIVATE" | jq 'length')
OV_COUNT=$(printf '%s' "$DISPLAY_OVERRIDES" | jq 'length')

if [ "$MODE" = "--stdout" ]; then
  printf '%s\n' "$JSON"
  echo "checked $OUT — named_private: ${NP_COUNT}, display_overrides: ${OV_COUNT} entries (stdout mode, nothing written)" >&2
else
  printf '%s\n' "$JSON" > "$OUT"
  echo "synced $OUT — named_private: ${NP_COUNT}, display_overrides: ${OV_COUNT} entries" >&2
fi
